<?php
declare(strict_types=1);
const DB_PATH='/var/lib/hamkare-web/registrations.sqlite3';
const NOTIFY_CONFIG='/etc/hamkare-web-notify.json';
function reply(array $body,int $status=200):never{http_response_code($status);header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');header('X-Content-Type-Options: nosniff');echo json_encode($body,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function notify_bots(array $r):void{
 if(!is_file(NOTIFY_CONFIG)||is_link(NOTIFY_CONFIG))return;$c=json_decode((string)file_get_contents(NOTIFY_CONFIG),true);if(!is_array($c))return;
 $text="📥 ثبت درخواست جدید از وب‌سایت همکاره\nنام: {$r['name']}\nموبایل: {$r['phone']}\nاستان: {$r['province']}\nکد پیگیری: {$r['tracking']}\nحوزه: {$r['role']}\nشیوه همکاری: {$r['workMode']}";
 foreach(['telegram'=>'https://api.telegram.org/bot','bale'=>'https://tapi.bale.ai/bot'] as $n=>$base){$token=(string)($c[$n]['token']??'');$chat=(string)($c[$n]['chat_id']??'');if(!preg_match('/^[A-Za-z0-9_:.-]{20,256}$/',$token)||!preg_match('/^-?[0-9]{3,30}$/',$chat))continue;$ctx=stream_context_create(['http'=>['method'=>'POST','timeout'=>5,'ignore_errors'=>true,'header'=>"Content-Type: application/json\r\n",'content'=>json_encode(['chat_id'=>$chat,'text'=>$text],JSON_UNESCAPED_UNICODE)]]);@file_get_contents($base.rawurlencode($token).'/sendMessage',false,$ctx);}
}
if(($_SERVER['REQUEST_METHOD']??'')!=='POST')reply(['ok'=>false,'error'=>'روش درخواست مجاز نیست.'],405);
$origin=(string)($_SERVER['HTTP_ORIGIN']??'');if($origin!==''&&!in_array($origin,['https://adlisho.online','https://www.adlisho.online'],true))reply(['ok'=>false,'error'=>'مبدأ درخواست مجاز نیست.'],403);
if(!str_contains(strtolower((string)($_SERVER['CONTENT_TYPE']??'')),'application/json'))reply(['ok'=>false,'error'=>'نوع داده نامعتبر است.'],415);
$raw=file_get_contents('php://input',false,null,0,8193);if($raw===false||strlen($raw)>8192)reply(['ok'=>false,'error'=>'حجم درخواست بیش از حد مجاز است.'],413);$d=json_decode($raw,true);if(!is_array($d))reply(['ok'=>false,'error'=>'داده ارسالی نامعتبر است.'],400);
$name=preg_replace('/\s+/u',' ',trim((string)($d['name']??'')));$phone=preg_replace('/\D+/','',(string)($d['phone']??''));$province=trim((string)($d['province']??''));$a=is_array($d['answers']??null)?$d['answers']:[];$q1=(string)($a['q1']??'');$q2=(string)($a['q2']??'');$q3=(string)($a['q3']??'');$role=trim((string)($d['role']??$a['role']??'پشتیبانی متقاضیان'));$workMode=trim((string)($d['workMode']??$a['workMode']??($q3==='no'?'دورکاری':'حضوری')));
if(!is_string($name)||mb_strlen($name)<3||mb_strlen($name)>80||!preg_match('/^[\p{L}\p{M} \'\x{200c}’.-]+$/u',$name))reply(['ok'=>false,'error'=>'نام و نام خانوادگی معتبر وارد کنید.'],400);if(!preg_match('/^09\d{9}$/',$phone))reply(['ok'=>false,'error'=>'شماره موبایل معتبر نیست.'],400);if(!preg_match('/^(0[1-9]|[12][0-9]|3[01])$/',$province))reply(['ok'=>false,'error'=>'استان انتخاب‌شده معتبر نیست.'],400);if(!in_array($q1,['0','1','3','6'],true)||!in_array($q2,['diploma','bachelor','master'],true)||!in_array($q3,['yes','no'],true))reply(['ok'=>false,'error'=>'پاسخ‌های ارزیابی کامل نیست.'],400);if(!in_array($role,['پشتیبانی متقاضیان','هماهنگی و عملیات','فنی و صنعتی','نماینده استانی'],true)||!in_array($workMode,['حضوری','دورکاری','ترکیبی','قابل مذاکره'],true))reply(['ok'=>false,'error'=>'حوزه یا شیوه همکاری معتبر نیست.'],400);
try{$db=new PDO('sqlite:'.DB_PATH,null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$db->exec("PRAGMA busy_timeout=5000; CREATE TABLE IF NOT EXISTS registrations(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,phone TEXT NOT NULL UNIQUE,province TEXT NOT NULL,answers TEXT NOT NULL,ip TEXT NOT NULL,tracking_code TEXT NOT NULL UNIQUE,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)");$ip=substr((string)($_SERVER['HTTP_CF_CONNECTING_IP']??$_SERVER['REMOTE_ADDR']??'unknown'),0,64);$s=$db->prepare("SELECT COUNT(*) FROM registrations WHERE ip=? AND created_at>=datetime('now','-1 hour')");$s->execute([$ip]);if((int)$s->fetchColumn()>=5)reply(['ok'=>false,'error'=>'تعداد درخواست‌ها بیش از حد مجاز است؛ کمی بعد تلاش کنید.'],429);$s=$db->prepare('SELECT 1 FROM registrations WHERE phone=?');$s->execute([$phone]);if($s->fetchColumn())reply(['ok'=>true,'existing'=>true,'message'=>'این شماره قبلاً ثبت شده است. برای بازیابی کد با پشتیبانی تماس بگیرید.']);$alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';$tracking='';foreach(unpack('C*',random_bytes(10))as$b)$tracking.=$alphabet[$b%strlen($alphabet)];$s=$db->prepare('INSERT INTO registrations(name,phone,province,answers,ip,tracking_code)VALUES(?,?,?,?,?,?)');$s->execute([$name,$phone,$province,json_encode(['q1'=>$q1,'q2'=>$q2,'q3'=>$q3,'role'=>$role,'workMode'=>$workMode],JSON_UNESCAPED_UNICODE),$ip,$tracking]);notify_bots(compact('name','phone','province','tracking','role','workMode'));reply(['ok'=>true,'tracking'=>$tracking],201);}catch(Throwable$e){error_log('hamkare registration failed: '.get_class($e));reply(['ok'=>false,'error'=>'ثبت درخواست موقتاً انجام نشد؛ دوباره تلاش کنید.'],503);}
