PRAGMA foreign_keys = ON;
CREATE TABLE admins (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE settings (setting_key TEXT PRIMARY KEY, setting_value TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE gateways (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, phone_number TEXT, operator_name TEXT, device_model TEXT, android_version TEXT, app_version TEXT, api_token_hash TEXT NOT NULL UNIQUE, pairing_hash TEXT, pairing_expires TEXT, status TEXT NOT NULL DEFAULT 'offline' CHECK(status IN ('offline','online')), last_seen TEXT, enabled INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL);
CREATE TABLE contacts (id INTEGER PRIMARY KEY AUTOINCREMENT, phone TEXT NOT NULL UNIQUE, display_name TEXT, consent_status TEXT NOT NULL DEFAULT 'unknown' CHECK(consent_status IN ('unknown','opted_in','opted_out')), source TEXT, created_at TEXT NOT NULL);
CREATE TABLE contact_groups (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL);
CREATE TABLE contact_group_members (group_id INTEGER NOT NULL, contact_id INTEGER NOT NULL, PRIMARY KEY(group_id,contact_id), FOREIGN KEY(group_id) REFERENCES contact_groups(id) ON DELETE CASCADE, FOREIGN KEY(contact_id) REFERENCES contacts(id) ON DELETE CASCADE);
CREATE TABLE campaigns (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, body TEXT NOT NULL, gateway_id INTEGER, status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','queued','running','paused','completed','cancelled')), test_mode INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, started_at TEXT, ended_at TEXT, FOREIGN KEY(gateway_id) REFERENCES gateways(id) ON DELETE SET NULL);
CREATE TABLE sms_jobs (id INTEGER PRIMARY KEY AUTOINCREMENT, job_uuid TEXT NOT NULL UNIQUE, campaign_id INTEGER, gateway_id INTEGER, phone TEXT NOT NULL, body TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'queued' CHECK(status IN ('queued','processing','sent','delivered','failed','cancelled')), attempts INTEGER NOT NULL DEFAULT 0, idempotency_key TEXT NOT NULL UNIQUE, error_text TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, FOREIGN KEY(campaign_id) REFERENCES campaigns(id) ON DELETE SET NULL, FOREIGN KEY(gateway_id) REFERENCES gateways(id) ON DELETE SET NULL);
CREATE INDEX sms_jobs_gateway_status_id ON sms_jobs(gateway_id,status,id);
CREATE TABLE sms_events (id INTEGER PRIMARY KEY AUTOINCREMENT, job_id INTEGER NOT NULL, event_type TEXT NOT NULL, detail TEXT, created_at TEXT NOT NULL, FOREIGN KEY(job_id) REFERENCES sms_jobs(id) ON DELETE CASCADE);
CREATE TABLE blocklist (phone TEXT PRIMARY KEY, reason TEXT, created_at TEXT NOT NULL);
CREATE TABLE telegram_logs (id INTEGER PRIMARY KEY AUTOINCREMENT, event_type TEXT NOT NULL, result TEXT NOT NULL, detail TEXT, created_at TEXT NOT NULL);
CREATE TABLE audit_logs (id INTEGER PRIMARY KEY AUTOINCREMENT, admin_id INTEGER, action TEXT NOT NULL, details TEXT, ip TEXT, created_at TEXT NOT NULL);
CREATE INDEX audit_logs_created_at ON audit_logs(created_at);
CREATE TABLE api_rate_limits (bucket_key TEXT PRIMARY KEY, window_start TEXT NOT NULL, hits INTEGER NOT NULL);
CREATE TABLE message_templates (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL UNIQUE, body TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE telegram_flows (chat_id TEXT PRIMARY KEY, state TEXT NOT NULL, data_json TEXT NOT NULL DEFAULT '{}', updated_at TEXT NOT NULL);
CREATE TABLE telegram_updates (update_id INTEGER PRIMARY KEY, processed_at TEXT NOT NULL);
CREATE TABLE sms_inbox (id INTEGER PRIMARY KEY AUTOINCREMENT, gateway_id INTEGER NOT NULL, phone TEXT NOT NULL, body TEXT NOT NULL, remote_id TEXT NOT NULL, received_at TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(gateway_id,remote_id), FOREIGN KEY(gateway_id) REFERENCES gateways(id) ON DELETE CASCADE);
CREATE INDEX sms_inbox_received_at ON sms_inbox(received_at DESC,id DESC);
CREATE TABLE media_library (id INTEGER PRIMARY KEY AUTOINCREMENT, file_id TEXT NOT NULL UNIQUE, file_unique_id TEXT, title TEXT NOT NULL, mime_type TEXT NOT NULL DEFAULT 'image/jpeg', size_bytes INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL);
CREATE INDEX media_library_created_at ON media_library(created_at DESC,id DESC);
