<?php
require __DIR__.'/../app/common.php';
$method=$_SERVER['REQUEST_METHOD']??'GET';$path=parse_url($_SERVER['REQUEST_URI']??'',PHP_URL_PATH)?:'';$path=preg_replace('#.*/api/?#','',$path);$data=json_decode(file_get_contents('php://input'),true)?:[];$pdo=db();rate_limit('api',120,60);
if($method==='POST'&&$path==='gateway/enrollment/request'){
 rate_limit('enrollment',5,600);
 $requestId=strtolower((string)($data['request_id']??''));$pollSecret=(string)($data['poll_secret']??'');
 if(!preg_match('/^[a-f0-9]{32}$/',$requestId)||!preg_match('/^[A-Za-z0-9_-]{40,64}$/',$pollSecret))json_out(['error'=>'invalid_enrollment_request'],422);
 $name=trim((string)($data['device_name']??'Huawei Gateway'));$model=trim((string)($data['device_model']??''));$tokenSettings=telegram_settings();
 if($tokenSettings['token']===''||$tokenSettings['chat_id']==='')json_out(['error'=>'telegram_admin_not_configured'],503);
 $name=substr($name===''?'Android Gateway':$name,0,100);$phone=normalize_phone((string)($data['phone_number']??''));
 try{
  $insert=$pdo->prepare("INSERT OR IGNORE INTO gateway_enrollments(request_id,poll_secret_hash,device_name,phone_number,operator_name,device_model,android_version,app_version,status,created_at,expires_at) VALUES(?,?,?,?,?,?,?,?,'pending',CURRENT_TIMESTAMP,datetime('now','+15 minutes'))");
  $insert->execute([$requestId,hash('sha256',$pollSecret),$name,$phone,substr((string)($data['operator']??''),0,80),substr($model,0,120),substr((string)($data['android_version']??''),0,40),substr((string)($data['app_version']??''),0,40)]);
  $check=$pdo->prepare('SELECT poll_secret_hash,status FROM gateway_enrollments WHERE request_id=?');$check->execute([$requestId]);$stored=$check->fetch();
  if(!$stored||!hash_equals((string)$stored['poll_secret_hash'],hash('sha256',$pollSecret)))json_out(['error'=>'enrollment_request_conflict'],409);
  if($insert->rowCount()===0)json_out(['ok'=>true,'request_id'=>$requestId,'status'=>$stored['status']]);
  $keyboard=['inline_keyboard'=>[[['text'=>'✅ بررسی و اتصال گوشی','callback_data'=>'enroll:approve:'.$requestId],['text'=>'رد درخواست','callback_data'=>'enroll:reject:'.$requestId]]]];
  $message="درخواست اتصال گوشی جدید\nنام: $name\nمدل: ".($model?:'نامشخص')."\nAndroid: ".substr((string)($data['android_version']??'نامشخص'),0,40)."\nشماره سیم‌کارت: ".($phone?:'نامشخص')."\n\nاگر این درخواست از گوشی خودتان است، آن را تأیید کنید. هیچ کد فعالی وارد نمی‌شود.";
  telegram_api('sendMessage',['chat_id'=>$tokenSettings['chat_id'],'text'=>$message,'reply_markup'=>$keyboard]);
 }catch(Throwable $e){$pdo->prepare('DELETE FROM gateway_enrollments WHERE request_id=? AND status=\'pending\'')->execute([$requestId]);json_out(['error'=>'enrollment_request_failed'],503);}
 json_out(['ok'=>true,'request_id'=>$requestId,'status'=>'pending']);
}
if($method==='GET'&&$path==='gateway/enrollment/status'){
 $requestId=strtolower((string)($_GET['request_id']??''));$pollSecret=(string)($_GET['poll_secret']??'');
 if(!preg_match('/^[a-f0-9]{32}$/',$requestId)||!preg_match('/^[A-Za-z0-9_-]{40,64}$/',$pollSecret))json_out(['error'=>'invalid_enrollment_request'],422);
 $q=$pdo->prepare('SELECT id,status,gateway_id,token_enc,expires_at FROM gateway_enrollments WHERE request_id=? AND poll_secret_hash=?');$q->execute([$requestId,hash('sha256',$pollSecret)]);$r=$q->fetch();if(!$r)json_out(['error'=>'enrollment_not_found'],404);
 if($r['status']==='pending'&&strtotime((string)$r['expires_at'].' UTC')<time()){$pdo->prepare("UPDATE gateway_enrollments SET status='expired',handled_at=CURRENT_TIMESTAMP WHERE id=?")->execute([$r['id']]);json_out(['status'=>'expired']);}
 if($r['status']==='approved')json_out(['status'=>'approved','gateway_id'=>(int)$r['gateway_id'],'token'=>dec($r['token_enc'])]);
 json_out(['status'=>$r['status']]);
}
if($method==='POST'&&$path==='gateway/pair'){rate_limit('pair',10,600);$code=strtoupper(trim((string)($data['pairing_code']??'')));if(!preg_match('/^[A-F0-9]{8}$/',$code))json_out(['error'=>'invalid_code'],422);$q=$pdo->prepare('SELECT id,name FROM gateways WHERE pairing_hash=? AND pairing_expires>? AND enabled=1');$q->execute([hash('sha256',$code),gmdate('Y-m-d H:i:s')]);$g=$q->fetch();if(!$g)json_out(['error'=>'expired_or_invalid_code'],401);$token=rtrim(strtr(base64_encode(random_bytes(48)),'+/','-_'),'=');$pdo->prepare('UPDATE gateways SET api_token_hash=?,pairing_hash=NULL,pairing_expires=NULL,device_model=?,android_version=?,app_version=?,phone_number=?,operator_name=?,status=\'online\',last_seen=CURRENT_TIMESTAMP WHERE id=?')->execute([hash('sha256',$token),substr((string)($data['device_model']??''),0,120),substr((string)($data['android_version']??''),0,40),substr((string)($data['app_version']??''),0,40),normalize_phone((string)($data['phone_number']??'')),substr((string)($data['operator']??''),0,80),$g['id']]);notify_telegram('gateway_online','Gateway آنلاین شد: '.$g['name']);json_out(['token'=>$token,'gateway_id'=>(int)$g['id'],'name'=>$g['name']]);}
if(!str_starts_with($path,'gateway/'))json_out(['error'=>'not_found'],404);$g=api_auth();
if($method==='POST'&&$path==='gateway/enrollment/claimed'){$q=$pdo->prepare("UPDATE gateway_enrollments SET status='claimed',token_enc=NULL,handled_at=CURRENT_TIMESTAMP WHERE gateway_id=? AND status='approved'");$q->execute([$g['id']]);json_out(['ok'=>true]);}
if($method==='POST'&&$path==='gateway/inbox'){$sender=trim((string)($data['phone']??''));$body=trim((string)($data['body']??''));$remote=trim((string)($data['remote_id']??''));$received=trim((string)($data['received_at']??''));if(!preg_match('/^\+?[0-9A-Za-z*#.-]{3,40}$/',$sender)||$body===''||strlen($body)>6000||!preg_match('/^[a-f0-9]{32,64}$/i',$remote))json_out(['error'=>'invalid_message'],422);try{$dt=new DateTimeImmutable($received?:'now');$receivedUtc=$dt->setTimezone(new DateTimeZone('UTC'))->format('Y-m-d H:i:s');}catch(Throwable $e){$receivedUtc=gmdate('Y-m-d H:i:s');}$q=$pdo->prepare('INSERT OR IGNORE INTO sms_inbox(gateway_id,phone,body,remote_id,received_at,created_at) VALUES(?,?,?,?,?,CURRENT_TIMESTAMP)');$q->execute([$g['id'],$sender,$body,strtolower($remote),$receivedUtc]);json_out(['ok'=>true,'inserted'=>$q->rowCount()===1]);}
if($method==='POST'&&$path==='gateway/heartbeat'){$q=$pdo->prepare('SELECT name,status FROM gateways WHERE id=?');$q->execute([$g['id']]);$before=$q->fetch();$pdo->prepare('UPDATE gateways SET status=\'online\',last_seen=CURRENT_TIMESTAMP,device_model=?,android_version=?,app_version=?,phone_number=?,operator_name=? WHERE id=?')->execute([substr((string)($data['device_model']??''),0,120),substr((string)($data['android_version']??''),0,40),substr((string)($data['app_version']??''),0,40),normalize_phone((string)($data['phone_number']??'')),substr((string)($data['operator']??''),0,80),$g['id']]);if($before&&$before['status']==='offline')notify_telegram('gateway_online','Gateway آنلاین شد: '.$before['name']);json_out(['ok'=>true,'server_time'=>gmdate(DATE_ATOM)]);}
if($method==='GET'&&$path==='gateway/jobs'){$pdo->prepare('UPDATE gateways SET status=\'online\',last_seen=CURRENT_TIMESTAMP WHERE id=?')->execute([$g['id']]);$interval=max(30,(int)($pdo->query("SELECT setting_value FROM settings WHERE setting_key='send_interval_seconds'")->fetchColumn()?:30));$last=$pdo->prepare("SELECT updated_at FROM sms_jobs WHERE gateway_id=? AND status IN ('processing','sent','delivered') ORDER BY updated_at DESC LIMIT 1");$last->execute([$g['id']]);$recent=$last->fetchColumn();if($recent&&strtotime((string)$recent)>time()-$interval)json_out(['jobs'=>[],'poll_after_seconds'=>max(5,$interval-(time()-strtotime((string)$recent)))]);$pdo->beginTransaction();$q=$pdo->prepare("SELECT j.id,j.job_uuid,j.phone,j.body,j.campaign_id FROM sms_jobs j LEFT JOIN campaigns c ON c.id=j.campaign_id WHERE j.gateway_id=? AND j.status='queued' AND COALESCE(c.test_mode,0)=0 AND (c.status IN ('queued','running') OR c.id IS NULL) ORDER BY j.id LIMIT 1");$q->execute([$g['id']]);$jobs=$q->fetchAll();foreach($jobs as $j){$pdo->prepare("UPDATE sms_jobs SET status='processing',attempts=attempts+1,updated_at=CURRENT_TIMESTAMP WHERE id=?")->execute([$j['id']]);if($j['campaign_id'])$pdo->prepare("UPDATE campaigns SET status='running',started_at=COALESCE(started_at,CURRENT_TIMESTAMP) WHERE id=?")->execute([$j['campaign_id']]);unset($j['campaign_id']);}$pdo->commit();json_out(['jobs'=>$jobs,'poll_after_seconds'=>$interval]);}
if($method==='POST'&&preg_match('#^gateway/jobs/([0-9]+)/(sent|delivered|failed)$#',$path,$m)){$id=(int)$m[1];$ev=$m[2];$status=$ev==='sent'?'sent':($ev==='delivered'?'delivered':'failed');$pdo->beginTransaction();$q=$pdo->prepare('SELECT id,status FROM sms_jobs WHERE id=? AND gateway_id=?');$q->execute([$id,$g['id']]);$job=$q->fetch();if(!$job){$pdo->rollBack();json_out(['error'=>'job_not_found'],404);}if($job['status']!=='delivered'&&$job['status']!=='failed'){$pdo->prepare('UPDATE sms_jobs SET status=?,error_text=?,updated_at=CURRENT_TIMESTAMP WHERE id=?')->execute([$status,$status==='failed'?substr((string)($data['error']??'SMS send failed'),0,500):null,$id]);$pdo->prepare('INSERT INTO sms_events(job_id,event_type,detail,created_at) VALUES(?,?,?,CURRENT_TIMESTAMP)')->execute([$id,$ev,substr((string)($data['detail']??''),0,500)]);}$pdo->commit();if($status==='failed')notify_telegram('sms_failure','ارسال ناموفق بود. Job '.$id.': '.substr((string)($data['error']??''),0,250));json_out(['ok'=>true,'status'=>$status]);}
json_out(['error'=>'not_found'],404);
