<?php
require __DIR__.'/../app/common.php';
$method=$_SERVER['REQUEST_METHOD']??'GET';$path=parse_url($_SERVER['REQUEST_URI']??'',PHP_URL_PATH)?:'';$path=preg_replace('#.*/api/?#','',$path);$data=json_decode(file_get_contents('php://input'),true)?:[];$pdo=db();rate_limit('api',120,60);
if($method==='POST'&&$path==='gateway/pair'){rate_limit('pair',10,600);$code=strtoupper(trim((string)($data['pairing_code']??'')));if(!preg_match('/^[A-F0-9]{8}$/',$code))json_out(['error'=>'invalid_code'],422);$q=$pdo->prepare('SELECT id,name FROM gateways WHERE pairing_hash=? AND pairing_expires>NOW() AND enabled=1');$q->execute([hash('sha256',$code)]);$g=$q->fetch();if(!$g)json_out(['error'=>'expired_or_invalid_code'],401);$token=rtrim(strtr(base64_encode(random_bytes(48)),'+/','-_'),'=');$pdo->prepare('UPDATE gateways SET api_token_hash=?,pairing_hash=NULL,pairing_expires=NULL,device_model=?,android_version=?,app_version=?,phone_number=?,operator_name=?,status=\'online\',last_seen=NOW() WHERE id=?')->execute([hash('sha256',$token),substr((string)($data['device_model']??''),0,120),substr((string)($data['android_version']??''),0,40),substr((string)($data['app_version']??''),0,40),normalize_phone((string)($data['phone_number']??'')),substr((string)($data['operator']??''),0,80),$g['id']]);json_out(['token'=>$token,'gateway_id'=>(int)$g['id'],'name'=>$g['name']]);}
if(!str_starts_with($path,'gateway/'))json_out(['error'=>'not_found'],404);$g=api_auth();
if($method==='POST'&&$path==='gateway/heartbeat'){$pdo->prepare('UPDATE gateways SET status=\'online\',last_seen=NOW(),device_model=?,android_version=?,app_version=?,phone_number=?,operator_name=? WHERE id=?')->execute([substr((string)($data['device_model']??''),0,120),substr((string)($data['android_version']??''),0,40),substr((string)($data['app_version']??''),0,40),normalize_phone((string)($data['phone_number']??'')),substr((string)($data['operator']??''),0,80),$g['id']]);json_out(['ok'=>true,'server_time'=>gmdate(DATE_ATOM)]);}
if($method==='GET'&&$path==='gateway/jobs'){$pdo->prepare('UPDATE gateways SET status=\'online\',last_seen=NOW() WHERE id=?')->execute([$g['id']]);$interval=max(30,(int)($pdo->query("SELECT setting_value FROM settings WHERE setting_key='send_interval_seconds'")->fetchColumn()?:30));$last=$pdo->prepare("SELECT updated_at FROM sms_jobs WHERE gateway_id=? AND status IN ('processing','sent','delivered') ORDER BY updated_at DESC LIMIT 1");$last->execute([$g['id']]);$recent=$last->fetchColumn();if($recent&&strtotime((string)$recent)>time()-$interval)json_out(['jobs'=>[],'poll_after_seconds'=>max(5,$interval-(time()-strtotime((string)$recent)))]);$pdo->beginTransaction();$q=$pdo->prepare("SELECT j.id,j.job_uuid,j.phone,j.body,j.campaign_id FROM sms_jobs j LEFT JOIN campaigns c ON c.id=j.campaign_id WHERE j.gateway_id=? AND j.status='queued' AND COALESCE(c.test_mode,0)=0 AND (c.status IN ('queued','running') OR c.id IS NULL) ORDER BY j.id LIMIT 1 FOR UPDATE");$q->execute([$g['id']]);$jobs=$q->fetchAll();foreach($jobs as $j){$pdo->prepare("UPDATE sms_jobs SET status='processing',attempts=attempts+1,updated_at=NOW() WHERE id=?")->execute([$j['id']]);if($j['campaign_id'])$pdo->prepare("UPDATE campaigns SET status='running',started_at=COALESCE(started_at,NOW()) WHERE id=?")->execute([$j['campaign_id']]);unset($j['campaign_id']);}$pdo->commit();json_out(['jobs'=>$jobs,'poll_after_seconds'=>$interval]);}
if($method==='POST'&&preg_match('#^gateway/jobs/([0-9]+)/(sent|delivered|failed)$#',$path,$m)){$id=(int)$m[1];$ev=$m[2];$status=$ev==='sent'?'sent':($ev==='delivered'?'delivered':'failed');$pdo->beginTransaction();$q=$pdo->prepare('SELECT id,status FROM sms_jobs WHERE id=? AND gateway_id=? FOR UPDATE');$q->execute([$id,$g['id']]);$job=$q->fetch();if(!$job){$pdo->rollBack();json_out(['error'=>'job_not_found'],404);}if($job['status']!=='delivered'&&$job['status']!=='failed'){$pdo->prepare('UPDATE sms_jobs SET status=?,error_text=?,updated_at=NOW() WHERE id=?')->execute([$status,$status==='failed'?substr((string)($data['error']??'SMS send failed'),0,500):null,$id]);$pdo->prepare('INSERT INTO sms_events(job_id,event_type,detail,created_at) VALUES(?,?,?,NOW())')->execute([$id,$ev,substr((string)($data['detail']??''),0,500)]);}$pdo->commit();json_out(['ok'=>true,'status'=>$status]);}
json_out(['error'=>'not_found'],404);
